---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangfan
--- DateTime: 2020/12/6 12:41
--- 基于Love2D引擎的测试程序

local luaPhyClass = require("../LuaPhysics2D")
local luaPhy = luaPhyClass.New()
local worldOri = {x = 0,y = 0}
local bodiesId = {}

local function InitLuaPhy()
    love.window.setTitle("Lua Physics 2D Tester -create by yangfan 2020-12-6")
    --
    local wid,hei = love.graphics.getDimensions()
    worldOri.x = wid / 2
    worldOri.y = hei / 2
    --
    luaPhy:Init()
    local groundBodyId = luaPhy:CreatePhysicsBodyRectangle(500,100,10)
    local groundBody = luaPhy:GetPhysicsBodyWithId(groundBodyId)
    luaPhy:SetPhysicsBodyRotation(groundBodyId,3)
    luaPhy:GetPhysicsBodyWithId(groundBodyId).enable = false
    local cubeBodyId = luaPhy:CreatePhysicsBodyRectangle(50,50,10)
    local cubeBody = luaPhy:GetPhysicsBodyWithId(cubeBodyId)
    cubeBody.position.y = 180
    local circleBodyId = luaPhy:CreatePhysicsBodyCircle(30,30)
    local circleBody = luaPhy:GetPhysicsBodyWithId(circleBodyId)
    circleBody.position.x = 100
    circleBody.position.y = 250
    table.insert(bodiesId,groundBodyId)
    table.insert(bodiesId,cubeBodyId)
    table.insert(bodiesId,circleBodyId)
end

local function drawBody(graphics,bodyId)
    local vertexs = luaPhy:GetPhysicsBodyVertexsWithId(bodyId)
    local vertexCnt = #vertexs
    if vertexCnt <= 0 then
        return
    end
    local nextIndex = 0
    local p1 = {x = 0, y = 0}
    local p2 = {x = 0, y = 0}
    for i = 1,vertexCnt do
        p1.x = worldOri.x - vertexs[i].x
        p1.y = worldOri.y - vertexs[i].y
        nextIndex = i + 1 <= vertexCnt and i + 1 or 1
        p2.x = worldOri.x - vertexs[nextIndex].x
        p2.y = worldOri.y - vertexs[nextIndex].y
        graphics.line(p1.x,p1.y,p2.x,p2.y)
    end
end

function love.load()
    InitLuaPhy()
end

function love.quit()
    if luaPhy then
        luaPhy:UnInit()
    end
end

function love.update(dt)
    if luaPhy then
        luaPhy:RunPhysicsStep(dt * 500)
    end
end

function love.draw()
    love.graphics.setLineWidth(3)
    love.graphics.setLineStyle('smooth')
    for i = 1,#bodiesId do
        love.graphics.setColor(1/i,2/i,3/i,1)
        drawBody(love.graphics,bodiesId[i])
    end
end
